export const uiLabels = {
  appTitle: '行動リプレイ',
  lead: 'BattleEngine が生成した Replay を行動単位で表示します。通常表示では内部IDを隠し、Debug領域で確認できます。',
  first: '最初',
  previous: '前へ',
  next: '次へ',
  tenForward: '+10',
  hundredForward: '+100',
  last: '最後',
  autoplay: '自動再生',
  pause: '一時停止',
  jump: '行動番号',
  speed: '再生速度',
  slow: '遅い',
  normal: '通常',
  fast: '速い',
  loading: '読み込み中',
  loadFailed: 'リプレイの読み込みに失敗しました',
  running: '戦闘中',
  ally: '味方',
  enemy: '敵',
  acted: '今回の行動者',
  nextActor: '次の行動',
  attackTarget: '攻撃対象',
  healTarget: '回復対象',
  defeated: '戦闘不能',
  hp: 'HP',
  mp: 'MP',
  actionRecovery: '行動時回復',
  hpr: 'HPR',
  mpr: 'MPR',
  draw: 'ドロー',
  ds: 'DS',
  drawProgress: '進捗',
  hand: '手札',
  deckDebug: '山札・捨て札',
  drawDebug: 'ドロー進行の詳細',
  cardDebug: 'カード試行の詳細',
  rawDebug: '生イベント',
  none: 'なし',
}

export function resultLabel(result: string, endReason: string): string {
  const results: Record<string, string> = {
    ally_win: '勝利',
    ally_loss: '敗北',
    draw: '引き分け',
    undecided: '戦闘中',
  }
  const reasons: Record<string, string> = {
    enemy_defeated: '敵を撃破',
    ally_defeated: '味方が戦闘不能',
    all_defeated: '双方戦闘不能',
    simulation_safety_limit: '最大行動数',
    no_actor: '行動者なし',
    running: '進行中',
  }
  return `${results[result] ?? result} / ${reasons[endReason] ?? endReason}`
}
